#!/usr/bin/env python3
"""Self-host the three typefaces, so the headline font starts downloading
with the HTML instead of after a round trip to Google.

Every page's largest contentful paint is text set in Archivo. Loaded from
Google Fonts, that glyph data cannot start downloading until the browser
has fetched fonts.googleapis.com's stylesheet and read the file URLs out
of it -- two hosts, one after the other, before the first heading can be
painted in its own face. Served from assets/fonts/ and preloaded from the
<head>, the file is in flight before the stylesheets have been parsed.

This tool fetches Google's own CSS for the families the site uses, keeps
the latin and latin-ext subsets (latin-ext is only downloaded for a page
that needs it, thanks to unicode-range), saves the woff2 files under
readable names and writes assets/css/fonts.css with the same @font-face
rules pointing at them. Re-run it to pick up a new font version; nothing
else changes.

Run from the repo root:  python3 tools/build_fonts.py
"""

import os
import re
import sys
import urllib.request

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(REPO_ROOT, "assets", "fonts")
CSS_OUT = os.path.join(REPO_ROOT, "assets", "css", "fonts.css")

GOOGLE_CSS = ("https://fonts.googleapis.com/css2"
              "?family=Archivo:wdth,wght@62..125,300..900"
              "&family=IBM+Plex+Mono:wght@400;600"
              "&family=Roboto:wght@400;500&display=swap")
# Google serves woff2 with unicode-range subsets only to a browser that
# understands them.
USER_AGENT = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
              "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
SUBSETS = ("latin", "latin-ext")

FACE_RE = re.compile(r"/\* (\S+) \*/\s*@font-face \{(.*?)\}", re.S)


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def prop(body, name):
    m = re.search(name + r": ([^;]+);", body)
    return m.group(1).strip() if m else None


def file_name(family, weight, subset):
    slug = family.lower().replace(" ", "-")
    w = weight.replace(" ", "-")
    return f"{slug}-{w}-{subset}.woff2"


def merge_weights(a, b):
    """Two weight declarations for one file become one range: Roboto is
    served as a variable file listed once per requested weight."""
    values = sorted({int(v) for v in (a + " " + b).split()})
    return f"{values[0]} {values[-1]}" if len(values) > 1 else str(values[0])


def parse_faces(css):
    """One record per font file in a wanted subset, in Google's order."""
    faces = {}
    for subset, body in FACE_RE.findall(css):
        if subset not in SUBSETS:
            continue
        url = re.search(r"url\(([^)]+)\)", body).group(1)
        family = prop(body, "font-family").strip("'")
        weight = prop(body, "font-weight")
        if url in faces:
            weight = merge_weights(faces[url]["weight"], weight)
        faces[url] = {
            "family": family, "subset": subset, "weight": weight,
            "style": prop(body, "font-style"), "stretch": prop(body, "font-stretch"),
            "unicode_range": prop(body, "unicode-range"), "url": url,
            "file": file_name(family, weight, subset),
        }
    return list(faces.values())


def face_rule(face):
    lines = ["@font-face {",
             f"  font-family: '{face['family']}';",
             f"  font-style: {face['style']};",
             f"  font-weight: {face['weight']};"]
    if face["stretch"]:
        lines.append(f"  font-stretch: {face['stretch']};")
    lines += ["  font-display: swap;",
              f"  src: url(../fonts/{face['file']}) format('woff2');",
              f"  unicode-range: {face['unicode_range']};",
              "}"]
    return "\n".join(lines)


def fonts_css(faces):
    head = ("/* Generated by tools/build_fonts.py from Google Fonts' own CSS.\n"
            "   Edit that tool, not this file. */\n\n")
    rules = [f"/* {face['family']} {face['weight']} -- {face['subset']} */\n"
             + face_rule(face) for face in faces]
    return head + "\n\n".join(rules) + "\n"


def main():
    css = fetch(GOOGLE_CSS).decode("utf-8")
    faces = parse_faces(css)
    if not faces:
        raise SystemExit("Google returned no latin @font-face blocks; UA rejected?")
    os.makedirs(FONT_DIR, exist_ok=True)
    for face in faces:
        path = os.path.join(FONT_DIR, face["file"])
        with open(path, "wb") as fh:
            fh.write(fetch(face["url"]))
        print(f"  {face['file']:40} {os.path.getsize(path) // 1024:4d} KB")
    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write(fonts_css(faces))
    print(f"assets/css/fonts.css: {len(faces)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
