#!/usr/bin/env python3
"""One stylesheet request per page: the bundles and the inline critical block.

A page used to link four sheets in series -- fonts.css, tokens.css,
werkstatt.css and its own page sheet -- and a phone on a slow connection
could not paint until all four had arrived: PageSpeed put the cost at
1.0-1.3 s of first paint on the homepage (2026-09-14). Now the two small
sheets that everything else depends on (the @font-face rules and the
tokens, ~9 KB raw, ~2.5 KB gzipped) travel inside the HTML as
<style id="critical">, so the browser asks for the typefaces as soon as
it has the document, and werkstatt.css plus the page sheet are served as
one file per page type:

    assets/css/bundle-home.css   werkstatt + home   (index.html)
    assets/css/bundle-site.css   werkstatt + site   (every service, hub and info page)
    assets/css/bundle-post.css   werkstatt + post   (the article, the privacy page)

The source sheets stay where they are and stay the thing you edit;
check_design_system.py and check_contrast.py read them, not the bundles.
The bundles strip comments and blank lines and nothing else, so a rule
in the bundle is byte-for-byte the rule in its source. werkstatt.css
comes first in every bundle, exactly the cascade the four links had.

fonts.css addresses the typefaces as ../fonts/ because it lives in
assets/css/; inlined into a page at the site root that path is rewritten
to assets/fonts/. The bundles keep living in assets/css/, so the one
url() in site.css needs no rewriting.

Run from the repo root, first in the pipeline (the generators and
apply_redesign.py import critical_markup() and bundle_link(), and
check_links.py wants the bundle files on disk):

    python3 tools/build_css.py

Bump apply_redesign.VERSION whenever a source sheet changes; the bundle
links carry it like every other asset.
"""

import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSS_DIR = os.path.join(REPO_ROOT, "assets", "css")

# The two sheets every page inlines, in cascade order.
CRITICAL = ("fonts", "tokens")
# The base sheet, then the page sheet, per page type.
BUNDLES = {
    "home": ("werkstatt", "home"),
    "site": ("werkstatt", "site"),
    "post": ("werkstatt", "post"),
}
COMMENT = re.compile(r"/\*.*?\*/", re.S)
BLANK_LINES = re.compile(r"\n\s*\n+")
FONT_URL = re.compile(r"url\(\.\./fonts/")

# A page's stylesheet block, as the generators and apply_redesign write it.
CRITICAL_RE = re.compile(r'<style id="critical">.*?</style>', re.S)
BUNDLE_LINK_RE = re.compile(r'<link rel="stylesheet" href="assets/css/bundle-[a-z]+\.css\?v=\d+">')


def read_sheet(name):
    with open(os.path.join(CSS_DIR, f"{name}.css"), encoding="utf-8") as fh:
        return fh.read()


def compact(css):
    """The sheet without its comments and blank lines; every rule verbatim."""
    css = COMMENT.sub("", css)
    css = BLANK_LINES.sub("\n", css)
    return css.strip() + "\n"


def bundle_css(kind):
    header = (f"/* Generated by tools/build_css.py from "
              f"{' + '.join(f'{n}.css' for n in BUNDLES[kind])}. "
              f"Edit those, then rerun the tool. */\n")
    return header + "".join(compact(read_sheet(name)) for name in BUNDLES[kind])


def critical_css():
    """fonts.css and tokens.css as one block that resolves from a page at the root."""
    css = "".join(compact(read_sheet(name)) for name in CRITICAL)
    return FONT_URL.sub("url(assets/fonts/", css)


def critical_markup():
    return f'<style id="critical">\n{critical_css()}</style>'


def bundle_link(kind, version):
    if kind not in BUNDLES:
        raise ValueError(f"no bundle named {kind!r}; one of {sorted(BUNDLES)}")
    return f'<link rel="stylesheet" href="assets/css/bundle-{kind}.css?v={version}">'


def stylesheets(kind, version):
    """The whole stylesheet block for a page of this type."""
    return f"{critical_markup()}\n{bundle_link(kind, version)}"


def bundle_kind(html):
    """Which bundle a page links, or None if it links none (the redirect stubs)."""
    m = re.search(r'assets/css/bundle-([a-z]+)\.css', html)
    return m.group(1) if m else None


def main():
    for kind in BUNDLES:
        path = os.path.join(CSS_DIR, f"bundle-{kind}.css")
        css = bundle_css(kind)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(css)
        print(f"  assets/css/bundle-{kind}.css  {len(css.encode('utf-8')) // 1024:3d} KB")
    print(f"  critical block               {len(critical_css().encode('utf-8')) // 1024:3d} KB inline")
    return 0


if __name__ == "__main__":
    sys.exit(main())
